#pragma once

// Name: pns, Version: 1


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Classes
//---------------------------------------------------------------------------

// Class CognitoIdp.CognitoIdpClientObject
// 0x0008 (FullSize[0x0030] - InheritedSize[0x0028])
class UCognitoIdpClientObject : public UObject
{
public:
	unsigned char                                      UnknownData_ZW9G[0x8];                                     // 0x0028(0x0008) MISSED OFFSET (PADDING)


	static UClass* StaticClass()
	{
		static UClass* ptr = UObject::FindClass("Class CognitoIdp.CognitoIdpClientObject");
		return ptr;
	}



	void VerifyUserAttribute(class UObject* WorldContextObject, bool* Success, const struct FVerifyUserAttributeRequest& VerifyUserAttributeRequest, struct FVerifyUserAttributeResult* VerifyUserAttributeResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void VerifySoftwareToken(class UObject* WorldContextObject, bool* Success, const struct FVerifySoftwareTokenRequest& VerifySoftwareTokenRequest, struct FVerifySoftwareTokenResult* VerifySoftwareTokenResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void UpdateUserPoolDomain(class UObject* WorldContextObject, bool* Success, const struct FUpdateUserPoolDomainRequest& UpdateUserPoolDomainRequest, struct FUpdateUserPoolDomainResult* UpdateUserPoolDomainResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void UpdateUserPoolClient(class UObject* WorldContextObject, bool* Success, const struct FUpdateUserPoolClientRequest& UpdateUserPoolClientRequest, struct FUpdateUserPoolClientResult* UpdateUserPoolClientResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void UpdateUserPool(class UObject* WorldContextObject, bool* Success, const struct FUpdateUserPoolRequest& UpdateUserPoolRequest, struct FUpdateUserPoolResult* UpdateUserPoolResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void UpdateUserAttributes(class UObject* WorldContextObject, bool* Success, const struct FUpdateUserAttributesRequest& UpdateUserAttributesRequest, struct FUpdateUserAttributesResult* UpdateUserAttributesResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void UpdateResourceServer(class UObject* WorldContextObject, bool* Success, const struct FUpdateResourceServerRequest& UpdateResourceServerRequest, struct FUpdateResourceServerResult* UpdateResourceServerResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void UpdateIdentityProvider(class UObject* WorldContextObject, bool* Success, const struct FUpdateIdentityProviderRequest& UpdateIdentityProviderRequest, struct FUpdateIdentityProviderResult* UpdateIdentityProviderResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void UpdateGroup(class UObject* WorldContextObject, bool* Success, const struct FUpdateGroupRequest& UpdateGroupRequest, struct FUpdateGroupResult* UpdateGroupResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void UpdateDeviceStatus(class UObject* WorldContextObject, bool* Success, const struct FUpdateDeviceStatusRequest& UpdateDeviceStatusRequest, struct FUpdateDeviceStatusResult* UpdateDeviceStatusResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void UpdateAuthEventFeedback(class UObject* WorldContextObject, bool* Success, const struct FUpdateAuthEventFeedbackRequest& UpdateAuthEventFeedbackRequest, struct FUpdateAuthEventFeedbackResult* UpdateAuthEventFeedbackResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void UntagResource(class UObject* WorldContextObject, bool* Success, const struct FCognitoIdpUntagResourceRequest& untagResourceRequest, struct FCognitoIdpUntagResourceResult* untagResourceResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void TagResource(class UObject* WorldContextObject, bool* Success, const struct FCognitoIdpTagResourceRequest& tagResourceRequest, struct FCognitoIdpTagResourceResult* tagResourceResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void StopUserImportJob(class UObject* WorldContextObject, bool* Success, const struct FStopUserImportJobRequest& StopUserImportJobRequest, struct FStopUserImportJobResult* StopUserImportJobResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void StartUserImportJob(class UObject* WorldContextObject, bool* Success, const struct FStartUserImportJobRequest& StartUserImportJobRequest, struct FStartUserImportJobResult* StartUserImportJobResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void SignUp(class UObject* WorldContextObject, bool* Success, const struct FSignUpRequest& SignUpRequest, struct FSignUpResult* SignUpResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void SetUserSettings(class UObject* WorldContextObject, bool* Success, const struct FSetUserSettingsRequest& SetUserSettingsRequest, struct FSetUserSettingsResult* SetUserSettingsResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void SetUserPoolMfaConfig(class UObject* WorldContextObject, bool* Success, const struct FSetUserPoolMfaConfigRequest& SetUserPoolMfaConfigRequest, struct FSetUserPoolMfaConfigResult* SetUserPoolMfaConfigResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void SetUserMFAPreference(class UObject* WorldContextObject, bool* Success, const struct FSetUserMFAPreferenceRequest& SetUserMFAPreferenceRequest, struct FSetUserMFAPreferenceResult* SetUserMFAPreferenceResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void SetUICustomization(class UObject* WorldContextObject, bool* Success, const struct FSetUICustomizationRequest& SetUICustomizationRequest, struct FSetUICustomizationResult* SetUICustomizationResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void SetRiskConfiguration(class UObject* WorldContextObject, bool* Success, const struct FSetRiskConfigurationRequest& SetRiskConfigurationRequest, struct FSetRiskConfigurationResult* SetRiskConfigurationResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void RespondToAuthChallenge(class UObject* WorldContextObject, bool* Success, const struct FRespondToAuthChallengeRequest& RespondToAuthChallengeRequest, struct FRespondToAuthChallengeResult* RespondToAuthChallengeResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ResendConfirmationCode(class UObject* WorldContextObject, bool* Success, const struct FResendConfirmationCodeRequest& ResendConfirmationCodeRequest, struct FResendConfirmationCodeResult* ResendConfirmationCodeResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ListUsersInGroup(class UObject* WorldContextObject, bool* Success, const struct FListUsersInGroupRequest& ListUsersInGroupRequest, struct FListUsersInGroupResult* ListUsersInGroupResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ListUsers(class UObject* WorldContextObject, bool* Success, const struct FListUsersRequest& ListUsersRequest, struct FListUsersResult* ListUsersResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ListUserPools(class UObject* WorldContextObject, bool* Success, const struct FListUserPoolsRequest& ListUserPoolsRequest, struct FListUserPoolsResult* ListUserPoolsResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ListUserPoolClients(class UObject* WorldContextObject, bool* Success, const struct FListUserPoolClientsRequest& ListUserPoolClientsRequest, struct FListUserPoolClientsResult* ListUserPoolClientsResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ListUserImportJobs(class UObject* WorldContextObject, bool* Success, const struct FListUserImportJobsRequest& ListUserImportJobsRequest, struct FListUserImportJobsResult* ListUserImportJobsResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ListTagsForResource(class UObject* WorldContextObject, bool* Success, const struct FCognitoIdpListTagsForResourceRequest& listTagsForResourceRequest, struct FCognitoIdpListTagsForResourceResult* listTagsForResourceResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ListResourceServers(class UObject* WorldContextObject, bool* Success, const struct FListResourceServersRequest& ListResourceServersRequest, struct FListResourceServersResult* ListResourceServersResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ListIdentityProviders(class UObject* WorldContextObject, bool* Success, const struct FListIdentityProvidersRequest& ListIdentityProvidersRequest, struct FListIdentityProvidersResult* ListIdentityProvidersResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ListGroups(class UObject* WorldContextObject, bool* Success, const struct FListGroupsRequest& ListGroupsRequest, struct FListGroupsResult* ListGroupsResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ListDevices(class UObject* WorldContextObject, bool* Success, const struct FListDevicesRequest& ListDevicesRequest, struct FListDevicesResult* ListDevicesResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void InitiateAuth(class UObject* WorldContextObject, bool* Success, const struct FInitiateAuthRequest& InitiateAuthRequest, struct FInitiateAuthResult* InitiateAuthResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void GlobalSignOut(class UObject* WorldContextObject, bool* Success, const struct FGlobalSignOutRequest& GlobalSignOutRequest, struct FGlobalSignOutResult* GlobalSignOutResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void GetUserPoolMfaConfig(class UObject* WorldContextObject, bool* Success, const struct FGetUserPoolMfaConfigRequest& GetUserPoolMfaConfigRequest, struct FGetUserPoolMfaConfigResult* GetUserPoolMfaConfigResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void GetUserAttributeVerificationCode(class UObject* WorldContextObject, bool* Success, const struct FGetUserAttributeVerificationCodeRequest& GetUserAttributeVerificationCodeRequest, struct FGetUserAttributeVerificationCodeResult* GetUserAttributeVerificationCodeResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void GetUser(class UObject* WorldContextObject, bool* Success, const struct FGetUserRequest& GetUserRequest, struct FGetUserResult* GetUserResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void GetUICustomization(class UObject* WorldContextObject, bool* Success, const struct FGetUICustomizationRequest& GetUICustomizationRequest, struct FGetUICustomizationResult* GetUICustomizationResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void GetSigningCertificate(class UObject* WorldContextObject, bool* Success, const struct FGetSigningCertificateRequest& GetSigningCertificateRequest, struct FGetSigningCertificateResult* GetSigningCertificateResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	struct FString GetServiceClientName();
	void GetIdentityProviderByIdentifier(class UObject* WorldContextObject, bool* Success, const struct FGetIdentityProviderByIdentifierRequest& GetIdentityProviderByIdentifierRequest, struct FGetIdentityProviderByIdentifierResult* GetIdentityProviderByIdentifierResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void GetGroup(class UObject* WorldContextObject, bool* Success, const struct FGetGroupRequest& GetGroupRequest, struct FGetGroupResult* GetGroupResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void GetDevice(class UObject* WorldContextObject, bool* Success, const struct FGetDeviceRequest& GetDeviceRequest, struct FGetDeviceResult* GetDeviceResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void GetCSVHeader(class UObject* WorldContextObject, bool* Success, const struct FGetCSVHeaderRequest& GetCSVHeaderRequest, struct FGetCSVHeaderResult* GetCSVHeaderResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ForgotPassword(class UObject* WorldContextObject, bool* Success, const struct FForgotPasswordRequest& ForgotPasswordRequest, struct FForgotPasswordResult* ForgotPasswordResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ForgetDevice(class UObject* WorldContextObject, bool* Success, const struct FForgetDeviceRequest& ForgetDeviceRequest, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DescribeUserPoolDomain(class UObject* WorldContextObject, bool* Success, const struct FDescribeUserPoolDomainRequest& DescribeUserPoolDomainRequest, struct FDescribeUserPoolDomainResult* DescribeUserPoolDomainResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DescribeUserPoolClient(class UObject* WorldContextObject, bool* Success, const struct FDescribeUserPoolClientRequest& DescribeUserPoolClientRequest, struct FDescribeUserPoolClientResult* DescribeUserPoolClientResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DescribeUserPool(class UObject* WorldContextObject, bool* Success, const struct FDescribeUserPoolRequest& DescribeUserPoolRequest, struct FDescribeUserPoolResult* DescribeUserPoolResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DescribeUserImportJob(class UObject* WorldContextObject, bool* Success, const struct FDescribeUserImportJobRequest& DescribeUserImportJobRequest, struct FDescribeUserImportJobResult* DescribeUserImportJobResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DescribeRiskConfiguration(class UObject* WorldContextObject, bool* Success, const struct FDescribeRiskConfigurationRequest& DescribeRiskConfigurationRequest, struct FDescribeRiskConfigurationResult* DescribeRiskConfigurationResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DescribeResourceServer(class UObject* WorldContextObject, bool* Success, const struct FDescribeResourceServerRequest& DescribeResourceServerRequest, struct FDescribeResourceServerResult* DescribeResourceServerResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DescribeIdentityProvider(class UObject* WorldContextObject, bool* Success, const struct FDescribeIdentityProviderRequest& DescribeIdentityProviderRequest, struct FDescribeIdentityProviderResult* DescribeIdentityProviderResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DeleteUserPoolDomain(class UObject* WorldContextObject, bool* Success, const struct FDeleteUserPoolDomainRequest& DeleteUserPoolDomainRequest, struct FDeleteUserPoolDomainResult* DeleteUserPoolDomainResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DeleteUserPoolClient(class UObject* WorldContextObject, bool* Success, const struct FDeleteUserPoolClientRequest& DeleteUserPoolClientRequest, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DeleteUserPool(class UObject* WorldContextObject, bool* Success, const struct FDeleteUserPoolRequest& DeleteUserPoolRequest, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DeleteUserAttributes(class UObject* WorldContextObject, bool* Success, const struct FDeleteUserAttributesRequest& DeleteUserAttributesRequest, struct FDeleteUserAttributesResult* DeleteUserAttributesResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DeleteUser(class UObject* WorldContextObject, bool* Success, const struct FDeleteUserRequest& DeleteUserRequest, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DeleteResourceServer(class UObject* WorldContextObject, bool* Success, const struct FDeleteResourceServerRequest& DeleteResourceServerRequest, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DeleteIdentityProvider(class UObject* WorldContextObject, bool* Success, const struct FDeleteIdentityProviderRequest& DeleteIdentityProviderRequest, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void DeleteGroup(class UObject* WorldContextObject, bool* Success, const struct FDeleteGroupRequest& DeleteGroupRequest, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void CreateUserPoolDomain(class UObject* WorldContextObject, bool* Success, const struct FCreateUserPoolDomainRequest& CreateUserPoolDomainRequest, struct FCreateUserPoolDomainResult* CreateUserPoolDomainResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void CreateUserPoolClient(class UObject* WorldContextObject, bool* Success, const struct FCreateUserPoolClientRequest& CreateUserPoolClientRequest, struct FCreateUserPoolClientResult* CreateUserPoolClientResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void CreateUserPool(class UObject* WorldContextObject, bool* Success, const struct FCreateUserPoolRequest& CreateUserPoolRequest, struct FCreateUserPoolResult* CreateUserPoolResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void CreateUserImportJob(class UObject* WorldContextObject, bool* Success, const struct FCreateUserImportJobRequest& CreateUserImportJobRequest, struct FCreateUserImportJobResult* CreateUserImportJobResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void CreateResourceServer(class UObject* WorldContextObject, bool* Success, const struct FCreateResourceServerRequest& CreateResourceServerRequest, struct FCreateResourceServerResult* CreateResourceServerResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void CreateIdentityProvider(class UObject* WorldContextObject, bool* Success, const struct FCreateIdentityProviderRequest& CreateIdentityProviderRequest, struct FCreateIdentityProviderResult* CreateIdentityProviderResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void CreateGroup(class UObject* WorldContextObject, bool* Success, const struct FCreateGroupRequest& CreateGroupRequest, struct FCreateGroupResult* CreateGroupResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	class UCognitoIdpClientObject* STATIC_CreateCognitoIdpObject(const struct FAWSCredentials& credentials, const struct FAWSClientConfiguration& clientConfiguration);
	void ConfirmSignUp(class UObject* WorldContextObject, bool* Success, const struct FConfirmSignUpRequest& ConfirmSignUpRequest, struct FConfirmSignUpResult* ConfirmSignUpResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ConfirmForgotPassword(class UObject* WorldContextObject, bool* Success, const struct FConfirmForgotPasswordRequest& ConfirmForgotPasswordRequest, struct FConfirmForgotPasswordResult* ConfirmForgotPasswordResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ConfirmDevice(class UObject* WorldContextObject, bool* Success, const struct FConfirmDeviceRequest& ConfirmDeviceRequest, struct FConfirmDeviceResult* ConfirmDeviceResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void ChangePassword(class UObject* WorldContextObject, bool* Success, const struct FChangePasswordRequest& ChangePasswordRequest, struct FChangePasswordResult* ChangePasswordResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AssociateSoftwareToken(class UObject* WorldContextObject, bool* Success, const struct FAssociateSoftwareTokenRequest& AssociateSoftwareTokenRequest, struct FAssociateSoftwareTokenResult* AssociateSoftwareTokenResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminUserGlobalSignOut(class UObject* WorldContextObject, bool* Success, const struct FAdminUserGlobalSignOutRequest& AdminUserGlobalSignOutRequest, struct FAdminUserGlobalSignOutResult* AdminUserGlobalSignOutResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminUpdateUserAttributes(class UObject* WorldContextObject, bool* Success, const struct FAdminUpdateUserAttributesRequest& AdminUpdateUserAttributesRequest, struct FAdminUpdateUserAttributesResult* AdminUpdateUserAttributesResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminUpdateDeviceStatus(class UObject* WorldContextObject, bool* Success, const struct FAdminUpdateDeviceStatusRequest& AdminUpdateDeviceStatusRequest, struct FAdminUpdateDeviceStatusResult* AdminUpdateDeviceStatusResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminUpdateAuthEventFeedback(class UObject* WorldContextObject, bool* Success, const struct FAdminUpdateAuthEventFeedbackRequest& AdminUpdateAuthEventFeedbackRequest, struct FAdminUpdateAuthEventFeedbackResult* AdminUpdateAuthEventFeedbackResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminSetUserSettings(class UObject* WorldContextObject, bool* Success, const struct FAdminSetUserSettingsRequest& AdminSetUserSettingsRequest, struct FAdminSetUserSettingsResult* AdminSetUserSettingsResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminSetUserPassword(class UObject* WorldContextObject, bool* Success, const struct FAdminSetUserPasswordRequest& AdminSetUserPasswordRequest, struct FAdminSetUserPasswordResult* AdminSetUserPasswordResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminSetUserMFAPreference(class UObject* WorldContextObject, bool* Success, const struct FAdminSetUserMFAPreferenceRequest& AdminSetUserMFAPreferenceRequest, struct FAdminSetUserMFAPreferenceResult* AdminSetUserMFAPreferenceResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminRespondToAuthChallenge(class UObject* WorldContextObject, bool* Success, const struct FAdminRespondToAuthChallengeRequest& AdminRespondToAuthChallengeRequest, struct FAdminRespondToAuthChallengeResult* AdminRespondToAuthChallengeResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminResetUserPassword(class UObject* WorldContextObject, bool* Success, const struct FAdminResetUserPasswordRequest& AdminResetUserPasswordRequest, struct FAdminResetUserPasswordResult* AdminResetUserPasswordResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminRemoveUserFromGroup(class UObject* WorldContextObject, bool* Success, const struct FAdminRemoveUserFromGroupRequest& AdminRemoveUserFromGroupRequest, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminListUserAuthEvents(class UObject* WorldContextObject, bool* Success, const struct FAdminListUserAuthEventsRequest& AdminListUserAuthEventsRequest, struct FAdminListUserAuthEventsResult* AdminListUserAuthEventsResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminListGroupsForUser(class UObject* WorldContextObject, bool* Success, const struct FAdminListGroupsForUserRequest& AdminListGroupsForUserRequest, struct FAdminListGroupsForUserResult* AdminListGroupsForUserResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminListDevices(class UObject* WorldContextObject, bool* Success, const struct FAdminListDevicesRequest& AdminListDevicesRequest, struct FAdminListDevicesResult* AdminListDevicesResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminLinkProviderForUser(class UObject* WorldContextObject, bool* Success, const struct FAdminLinkProviderForUserRequest& AdminLinkProviderForUserRequest, struct FAdminLinkProviderForUserResult* AdminLinkProviderForUserResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminInitiateAuth(class UObject* WorldContextObject, bool* Success, const struct FAdminInitiateAuthRequest& AdminInitiateAuthRequest, struct FAdminInitiateAuthResult* AdminInitiateAuthResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminGetUser(class UObject* WorldContextObject, bool* Success, const struct FAdminGetUserRequest& AdminGetUserRequest, struct FAdminGetUserResult* AdminGetUserResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminGetDevice(class UObject* WorldContextObject, bool* Success, const struct FAdminGetDeviceRequest& AdminGetDeviceRequest, struct FAdminGetDeviceResult* AdminGetDeviceResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminForgetDevice(class UObject* WorldContextObject, bool* Success, const struct FAdminForgetDeviceRequest& AdminForgetDeviceRequest, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminEnableUser(class UObject* WorldContextObject, bool* Success, const struct FAdminEnableUserRequest& AdminEnableUserRequest, struct FAdminEnableUserResult* AdminEnableUserResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminDisableUser(class UObject* WorldContextObject, bool* Success, const struct FAdminDisableUserRequest& AdminDisableUserRequest, struct FAdminDisableUserResult* AdminDisableUserResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminDisableProviderForUser(class UObject* WorldContextObject, bool* Success, const struct FAdminDisableProviderForUserRequest& AdminDisableProviderForUserRequest, struct FAdminDisableProviderForUserResult* AdminDisableProviderForUserResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminDeleteUserAttributes(class UObject* WorldContextObject, bool* Success, const struct FAdminDeleteUserAttributesRequest& AdminDeleteUserAttributesRequest, struct FAdminDeleteUserAttributesResult* AdminDeleteUserAttributesResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminDeleteUser(class UObject* WorldContextObject, bool* Success, const struct FAdminDeleteUserRequest& AdminDeleteUserRequest, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminCreateUser(class UObject* WorldContextObject, bool* Success, const struct FAdminCreateUserRequest& AdminCreateUserRequest, struct FAdminCreateUserResult* AdminCreateUserResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminConfirmSignUp(class UObject* WorldContextObject, bool* Success, const struct FAdminConfirmSignUpRequest& AdminConfirmSignUpRequest, struct FAdminConfirmSignUpResult* AdminConfirmSignUpResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AdminAddUserToGroup(class UObject* WorldContextObject, bool* Success, const struct FAdminAddUserToGroupRequest& AdminAddUserToGroupRequest, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
	void AddCustomAttributes(class UObject* WorldContextObject, bool* Success, const struct FAddCustomAttributesRequest& AddCustomAttributesRequest, struct FAddCustomAttributesResult* AddCustomAttributesResult, CognitoIdp_ECognitoIdpError* errorType, struct FString* errorMessage, const struct FLatentActionInfo& LatentInfo);
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
